# Output example: 
#    https://pipelines.actions.githubusercontent.com/G0duPD7L7sIO75aWBFOWZwmLVT2DK4aFvgSUJB6DMHj6Vqn9rO/_apis/pipelines/1/runs/119/signedlogcontent/3?urlExpires=2019-11-18T14%3A24%3A31.4537417Z&urlSigningMethod=HMACV1&urlSignature=BsOHbdk9pf8TD5srEj56%2BHE05ONNxBeOa2N9ChLgMfs%3D
name: Example Workflow
on: 
  - pull_request


jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
